[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
challenge = "39EXycGNJFySJCK61evbVbJ3JWj9wVsqRF7RbJq1fic3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
