services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8501:9000"
  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    environment:
      - APP_HOST=ezcalc-1.loums.cc